<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="MSTest" Version="4.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Exergism.DeploymentAttestation.Agent/Exergism.DeploymentAttestation.Agent.csproj" />
  </ItemGroup>
</Project>
